namespace: arista
name: eos
version: 1.0.0
readme: null
authors: null
description: null
license: null
license_file: null
tags: null
dependencies:
  network.common: '>=1.0'
repository: git@github.com:ansible-collection-migration/arista.eos.git
documentation: null
homepage: null
issues: null
