namespace: network
name: common
version: 1.0.0
readme: null
authors: null
description: null
license: null
license_file: null
tags: null
dependencies:
  cisco.iosxr: '>=1.0'
  juniper.junos: '>=1.0'
repository: git@github.com:ansible-collection-migration/network.common.git
documentation: null
homepage: null
issues: null
